# Generated by Django 6.0.2 on 2026-09-10 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0011_result_unique_student_exam_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('response_type', models.CharField(choices=[('faculty', 'Faculty Feedback'), ('course', 'Course Feedback'), ('general', 'General Feedback')], default='faculty', max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feedback_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('academic_year', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_assignments', to='quiz.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_assignments', to='quiz.facultyprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_assignments', to='quiz.subject')),
                ('feedback_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='feedback.feedbackform')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('rating', 'Rating 1-5'), ('yes_no', 'Yes / No'), ('text', 'Text'), ('choice', 'Multiple Choice')], default='rating', max_length=20)),
                ('option1', models.CharField(blank=True, max_length=255, null=True)),
                ('option2', models.CharField(blank=True, max_length=255, null=True)),
                ('option3', models.CharField(blank=True, max_length=255, null=True)),
                ('option4', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('feedback_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.feedbackform')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedbackassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='quiz.studentprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('selected_option', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbackquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.feedbackresponse')),
            ],
            options={
                'ordering': ['question__display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='feedbackresponse',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_student_feedback_response'),
        ),
        migrations.AddConstraint(
            model_name='feedbackanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_response_question_answer'),
        ),
    ]
