# Generated by Django 6.0.3 on 2026-07-29 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='academic_year',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='course',
            field=models.ForeignKey(default=1999, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
