# Generated by Django 6.0.2 on 2026-07-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
