# Generated by Django 6.0.2 on 2026-07-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default='sub001', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
