# Generated by Django 6.0.2 on 2026-07-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_facultyprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='quiz.exam'),
        ),
    ]
