# Generated by Django 6.0.3 on 2026-07-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questionpaper_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='academic_year',
            field=models.CharField(default=1999, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='semester',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=10),
        ),
    ]
