# Generated by Django 6.0.2 on 2026-07-18 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='file',
            field=models.FileField(default=1, upload_to='papers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject'),
        ),
    ]
