# Generated by Django 6.0.3 on 2026-07-29 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_academic_year_question_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='quiz.subject'),
        ),
    ]
