# Generated by Django 6.0.2 on 2026-07-18 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_questionpaper_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_ans',
            new_name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='semester',
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject'),
        ),
    ]
