# Generated by Django 6.0.2 on 2026-08-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_result_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
