# Generated by Django 6.0.2 on 2026-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_exam_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
