# Generated by Django 6.0.2 on 2026-08-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_studentprofile_aadhaar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.course'),
        ),
    ]
